# Generated by Django 3.2.25 on 2024-07-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240717_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
