# Generated by Django 3.2.25 on 2024-07-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.description'),
            preserve_default=False,
        ),
    ]
